'use client';
import {useEffect,useRef,useState} from 'react';
import type {Product,PricingGroup} from '@/lib/products';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Price} from '@/app/shared';
import Pricing from './pricing';
export default function Manager({initial,groups}:{initial:Product[];groups:PricingGroup[]}){
 const [products,setProducts]=useState(initial),[open,setOpen]=useState(false),[editing,setEditing]=useState<Product|null>(null),[remove,setRemove]=useState<Product|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const [selectedCode,setSelectedCode]=useState('');const formRef=useRef<HTMLFormElement>(null);
 const start=(p:Product|null)=>{setEditing(p);setSelectedCode(p?.pricing_code??'');setError('');setOpen(true)};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'start_product_creation',title:'آماده‌کردن محصول جدید',description:'Open the product creation form. This does not save or publish a product; the owner must fill and submit the visible form.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');start(null);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {formOpened:true,saved:false}}},{signal:controller.signal})).catch(console.error);return ()=>controller.abort()},[]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);if(editing)form.set('id',editing.id);try{const r=await fetch('/api/products',{method:'POST',body:form});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error||'ذخیره انجام نشد.');setOpen(false);setNotice('محصول ذخیره شد.');window.location.reload()}catch(e){setError(e instanceof Error?e.message:'ذخیره انجام نشد. دوباره تلاش کنید.')}finally{setBusy(false)}}
 async function erase(){if(!remove)return;setBusy(true);setError('');try{const r=await fetch('/api/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:remove.id})});const data=await r.json() as {error?:string};if(!r.ok)throw Error(data.error);setProducts(prev=>prev.filter(p=>p.id!==remove.id));setRemove(null);setNotice('محصول از ویترین حذف شد.')}catch(e){setError(e instanceof Error?e.message:'حذف انجام نشد.')}finally{setBusy(false)}}
 return <main className="collection manager"><div className="section-top"><div><span className="eyebrow">نقره گلبرگ</span><h1>مدیریت محصولات</h1><p>عکس، قیمت و توضیحات محصولات ویترین را اینجا وارد کنید.</p></div><button className="button" onClick={()=>start(null)}>+ افزودن محصول</button></div><Pricing groups={groups} products={products}/><p role="status">{notice}</p>{!products.length?<div className="empty"><h2>اولین محصولتان را اضافه کنید</h2><p>یک عکس واضح و نام محصول برای شروع کافی است.</p><button className="button" onClick={()=>start(null)}>افزودن اولین محصول</button></div>:<div className="manage-list">{products.map(p=><article key={p.id}><img src={'/api/images/'+p.image} alt={p.name}/><div><h2>{p.name}</h2><Price price={p.price}/>{p.pricing_code&&<p>کد {Number(p.pricing_code).toLocaleString('fa-IR')} · {p.weight}</p>}</div><div className="row-actions"><button onClick={()=>start(p)}>ویرایش</button><button onClick={()=>{setError('');setRemove(p)}}>حذف</button><a href={'/product/'+p.id}>مشاهده ↗</a></div></article>)}</div>}
 <Dialog open={open} onOpenChange={value=>{if(!busy)setOpen(value)}}><DialogContent className="product-dialog" dir="rtl" showCloseButton={false}><DialogTitle>{editing?'ویرایش محصول':'افزودن محصول'}</DialogTitle><DialogDescription>با انتخاب کد، قیمت از وزن و نرخ آن کد محاسبه می‌شود. بدون کد می‌توانید قیمت را دستی وارد کنید.</DialogDescription><form ref={formRef} onSubmit={save} key={editing?.id||'new'}><label>نام محصول<input name="name" required maxLength={120} defaultValue={editing?.name} placeholder="مثلاً انگشتر نقره گلبرگ"/></label><label>عکس محصول{editing&&<img className="edit-thumb" src={'/api/images/'+editing.image} alt="عکس فعلی محصول"/>}<input type="file" name="image" accept="image/jpeg,image/png,image/webp" required={!editing}/><small>JPG، PNG یا WebP؛ حداکثر ۸ مگابایت. {editing?'برای نگه‌داشتن عکس فعلی، این قسمت را خالی بگذارید.':''}</small></label><label>کد قیمت<select name="pricing_code" value={selectedCode} onChange={e=>setSelectedCode(e.target.value)}><option value="">بدون کد · قیمت دستی</option>{groups.map(g=><option key={g.code} value={g.code}>کد {Number(g.code).toLocaleString('fa-IR')} · گرمی {g.rate.toLocaleString('fa-IR')} تومان</option>)}</select></label><div className="form-row"><label>قیمت (تومان)<input name="price" disabled={!!selectedCode} inputMode="numeric" defaultValue={editing?.price??''} placeholder="مثلاً ۲۵۰۰۰۰۰"/></label><label>وزن (گرم؛ برای کد قیمت الزامی است)<input name="weight" required={!!selectedCode} maxLength={60} defaultValue={editing?.weight} placeholder="مثلاً ۴٫۵ گرم"/></label></div><label>توضیحات<textarea name="description" rows={4} maxLength={3000} defaultValue={editing?.description} placeholder="عیار، اندازه، نوع سنگ و سایر مشخصات"/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><button className="button" disabled={busy} type="submit">{busy?'در حال ذخیره…':'ذخیره و نمایش در ویترین'}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)}>انصراف</button></div></form></DialogContent></Dialog>
 <AlertDialog open={!!remove} onOpenChange={value=>{if(!value&&!busy)setRemove(null)}}><AlertDialogContent dir="rtl"><AlertDialogTitle>این محصول حذف شود؟</AlertDialogTitle><AlertDialogDescription>«{remove?.name}» و عکس آن از ویترین حذف می‌شوند.</AlertDialogDescription>{error&&<p className="error" role="alert">{error}</p>}<div className="form-actions"><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void erase()}}>{busy?'در حال حذف…':'حذف محصول'}</AlertDialogAction><AlertDialogCancel disabled={busy}>انصراف</AlertDialogCancel></div></AlertDialogContent></AlertDialog>
 </main>
}

